# Site settings
title: JKWC - Jack Kontou Wing Chun
email: info@jkwc.co.uk
description:
baseurl: "/jkwc_ws" # the subpath of your site, e.g. /blog/
url: "http://jkwc.co.uk" # the base hostname & protocol for your site
twitter_username: Jack_Kontou

# Build settings
markdown: kramdown
highlighter: rouge

# prose.io  settings
prose:
  siteurl: "http://jackkontouwingchun.github.io/"
  media: "img"
  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - _config.yml
    - /_layouts
    - /_includes
    - /fonts
    - /font-awesome
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"
