# Site settings
title: JKWC - Jack Kontou Wing Chun
email: info@jkwc.co.uk
description:
baseurl: "/jkwc_ws" # the subpath of your site, e.g. /blog/
url: "http://jkwc.co.uk" # the base hostname & protocol for your site
twitter_username: Jack_Kontou
paginate: 10

# Build settings
markdown: kramdown
highlighter: pygments

# prose.io  settings
prose:
  siteurl: "http://jackkontouwingchun.github.io/"
  media: "img"
  ignore:
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - _config.yml
    - /_layouts
    - /_includes
    - /fonts
    - /font-awesome
    - /js/bootstrap.js
    - /js/bootstrap.min.js
    - /js/jquery.js
    - /js/jquery.easing.min.js
    - /css/bootstrap.css
    - /css/bootstrap.min.css
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          placeholder: "A awesome Headline!"
      - name: "thumbnail"
        field:
          label: "Thumbnail"
          element: "text"
          placeholder: ""
      - name: "orientation"
        field:
          label: "Thumbnail"
          element: "select"
          placeholder: ""
          alterable: true
          options:
            - name: "Portrait"
              value: "portrait"
            - name: "Landscape"
              value: "landscape"
      - name: "focal-v"
        field:
          label: "Focal-V"
          element: "text"
          placeholder: ""
      - name: "focal-h"
        field:
          label: "Focal-H"
          element: "text"
          placeholder: ""
      - name: "category"
        field:
          element: "select"
          label: "Choose category"
          placeholder: "Choose category"
          alterable: true
          options:
            - name: "Text"
              value: "text"
            - name: "YouTube"
              value: "youtube"
            - name: "News"
              value: "news"